create index if not exists categories_parent_idx on public.categories(parent_id);
create index if not exists cart_items_variant_idx on public.cart_items(variant_id);

drop policy if exists "stores_public_read_active" on public.stores;
drop policy if exists "stores_vendor_owner_manage" on public.stores;
create policy "stores_select_public_or_owner" on public.stores for select to anon, authenticated using (status = 'active' or ((select auth.uid()) = owner_id and exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency'))));
create policy "stores_vendor_owner_insert" on public.stores for insert to authenticated with check ((select auth.uid()) = owner_id and status = 'pending' and exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));
create policy "stores_vendor_owner_update" on public.stores for update to authenticated using ((select auth.uid()) = owner_id and exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency'))) with check ((select auth.uid()) = owner_id and status = 'pending' and exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));
create policy "stores_vendor_owner_delete" on public.stores for delete to authenticated using ((select auth.uid()) = owner_id and status = 'pending' and exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));

drop policy if exists "products_public_read_active_store" on public.products;
drop policy if exists "products_vendor_owner_manage" on public.products;
create policy "products_select_public_or_owner" on public.products for select to anon, authenticated using ((status = 'active' and exists (select 1 from public.stores s where s.id = store_id and s.status = 'active')) or exists (select 1 from public.stores s join public.user_roles ur on ur.user_id = s.owner_id where s.id = store_id and s.owner_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));
create policy "products_vendor_owner_insert" on public.products for insert to authenticated with check (status = 'draft' and exists (select 1 from public.stores s join public.user_roles ur on ur.user_id = s.owner_id where s.id = store_id and s.owner_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));
create policy "products_vendor_owner_update" on public.products for update to authenticated using (exists (select 1 from public.stores s join public.user_roles ur on ur.user_id = s.owner_id where s.id = store_id and s.owner_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency'))) with check (status = 'draft' and exists (select 1 from public.stores s join public.user_roles ur on ur.user_id = s.owner_id where s.id = store_id and s.owner_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')));
create policy "products_vendor_owner_delete" on public.products for delete to authenticated using (exists (select 1 from public.stores s join public.user_roles ur on ur.user_id = s.owner_id where s.id = store_id and s.owner_id = (select auth.uid()) and ur.role in ('restaurant_vendor','fashion_vendor','car_dealer','umrah_agency')) and status = 'draft');

drop policy if exists "product_images_public_read_active" on public.product_images;
drop policy if exists "product_images_owner_manage" on public.product_images;
create policy "product_images_select_public_or_owner" on public.product_images for select to anon, authenticated using (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and p.status = 'active' and s.status = 'active') or exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_images_owner_insert" on public.product_images for insert to authenticated with check (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_images_owner_update" on public.product_images for update to authenticated using (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid()))) with check (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_images_owner_delete" on public.product_images for delete to authenticated using (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));

drop policy if exists "product_variants_public_read_active" on public.product_variants;
drop policy if exists "product_variants_owner_manage" on public.product_variants;
create policy "product_variants_select_public_or_owner" on public.product_variants for select to anon, authenticated using ((is_active and exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and p.status = 'active' and s.status = 'active')) or exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_variants_owner_insert" on public.product_variants for insert to authenticated with check (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_variants_owner_update" on public.product_variants for update to authenticated using (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid()))) with check (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
create policy "product_variants_owner_delete" on public.product_variants for delete to authenticated using (exists (select 1 from public.products p join public.stores s on s.id = p.store_id where p.id = product_id and s.owner_id = (select auth.uid())));
